name: Superdapp 
settings:
  DEVELOPMENT_TEAM: 99JJXS75CQ
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 0.0.1
options:
  bundleIdPrefix: com.superdapp
  deploymentTarget:
    iOS: "17.5"
  createIntermediateGroups: true
  preGenCommand: .github/scripts/pre.sh
  postGenCommand: .github/scripts/post.sh
packages:
  # capsule-swift-sdk:
  #   url: https://github.com/capsule-org/swift-sdk.git
  #   branch: initial-branch
  capsule-swift-sdk:
    path: ../swift-sdk
  SwiftCryptoTokenFormatter:
    url: https://github.com/gnosis/SwiftCryptoTokenFormatter.git
    branch: main
  OpenAPIClient:
    path: Library/API
  
targets:
  Superdapp:
    type: application
    platform: iOS
    sources:
      - path: Apps/iOS
        excludes:
          - Apps/iOS/PreviewContent/*
      - path: Apps/iOS/Resources/
        buildPhase: resources
      - path: .
        includes:
          - .env
        buildPhase: resources
    settings:
      DEVELOPMENT_ASSET_PATHS: Apps/iOS/PreviewContent
      PRODUCT_BUNDLE_IDENTIFIER: com.superdapp.blau
      SUPPORTED_PLATFORMS: [iphoneos, iphonesimulator]
      CODE_SIGN_ENTITLEMENTS: Apps/iOS/SupportingFiles/Superdapp.entitlements
      TARGETED_DEVICE_FAMILY: 1
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      GENERATE_INFOPLIST_FILE: true
      VALIDATE_WORKSPACE: true
      INFOPLIST_KEY_UISupportedInterfaceOrientations:
        [
          "UIInterfaceOrientationPortrait"
        ]
    dependencies:
      - package: SwiftCryptoTokenFormatter
        product: SwiftCryptoTokenFormatter
      - package: capsule-swift-sdk
        product: CapsuleSwift
      - package: OpenAPIClient
        product: OpenAPIClient
